spring:
  datasource:
    url: "jdbc:postgresql://postgresql:5432/biom?ApplicationName=JusticeWeb"
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 30000
      max-lifetime: 50000
      connection-timeout: 30000
      pool-name: "JusticeWeb"
  liquibase:
    change-log: "classpath:liquibase/db.changelog.xml"
    default-schema: "just"
  messages:
    basename: "i18n/messages"
    encoding: "UTF-8"

server:
  port: 80

locale:
  default: "ru"

user:
  default: "user@biom.kg"

content:
  items:
    count: 3
  base:
    path: "https://justice.biom.kg/upload"
  date:
    pattern: "dd.MM.yyyy"
